### ISSUE TITLE
ROC Data Assigned to Incorrect ROC

### ISSUE THREAD

**Issue by drberry85** [psi46/pxar#276]
Simon and Urs,

There is a problem with how the ROC data is assigned to a ROCs ID when there are bypassed ROCs on TBM Core A. It looks like the ROC data matching expects 8 ROCs on TBM Core A. So if there are only 7 ROCs on Core A, it will not look to TBM Core B for additional data, but instead just leave ROC 7 empty. Likewise, if there are two bypassed ROCs on TBM Core A, it will not display data for ROCs 6 and 7.

For example, if the you have the following configuration:
```nRocs 10 i2c: 0,2,3,4,5,6,8,9,10,15.```

You can see there are 6 ROCs on TBM Core A and 4 ROCs on TBM Core B for a total of 10 ROCs. But when you look that the results of the dac-dac scans you loose the data from ROCs with IDs 7 and 8. You can see the dac-dac scan results at https://drberry.web.cern.ch/drberry/M_FR_906_DacDacScan/ . I think this happens because it expects the data for ROC ID 7 and 8 to come before the first TBM trailer.

Doug

**Comment by simonspa** [comment]
Hi Doug,

thanks for your reply, if this is a requirement for you we will of course find and implement a solution. I have to think a bit about how to implement this in a clever way, also because currently running e.g. Core A with only 7 ROCs will flood you with warnings about token chain being too short (in the error_reporting branch that is).
If you browsed the code and have a good idea let me know!

/Simon

**Comment by simonspa** [comment]
Hi @drberry85 

since I'm currently working on a refactoring of the decoder modules to also allow more flexible DUT structures such as several ROCs on one DESER160 line I'm also again trying to find a solution here.

But first you have to remind me of the actual problem: is it, that all tests require consecutive numbering of the ROC id inn order to work?

Because when setting the I2C addresses manually (as you do above) at least the programming should be fine for all ROCs, just the readout will not produce a continuous ROC id chain but one with a hole at the end of TBM core alpha data stream.

As far as I see, the `PixTest` seem to use `pxarCore->_dut->getEnabledRocIDs()` to loop over the output data and this creates the problem, correct? If I have

```
nrocs 10 i2c: 0 1 2 3 4 5 6 8 9 10
```

then the DUT object returns

```
pxarCore =>> getEnabledRocIDs
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
pxarCore =>> getEnabledRocI2Caddr
[0, 1, 2, 3, 4, 5, 6, 8, 9, 10]
```

while the output data will contain `0 1 2 3 4 5 6` in TBM Alpha and `8 9 10` in TBM Beta since the ROC id counter isn't passed between the two instances, right?

So the only thing we need to implement is passing a token chain length plus offset to the decoder modules, so Core Alpha would get 
```
Token Chain length: 7
Offset: 0
```
and Beta
```
Token Chain length: 3
Offset: 7
```

Can you confirm this?

**Comment by drberry85** [comment]
Simon,

Responses below, I hope this doesn't break git...

But first you have to remind me of the actual problem: is it, that all
tests require consecutive numbering of the ROC id inn order to work?

There are two problems, one major and one minor.

The major problem is that if there is N missing ROCs on TBM Core A, then
the data for the first  N ROCs on TBM Core B is lost.

The minor issue is that the ROC data is associated with wrong ROC. This is
mostly a cosmetic issue at this point.

------------------------------------------------------------------------------------------

while the output data will contain 0 1 2 3 4 5 6 in TBM Alpha and 8 9 10 in
TBM Beta since the ROC id counter isn't passed between the two instances,
right?

Yes, this is the cause of the ROC mislabeling. And it may also cause the
data from ROC 8 to be associated with TBM Alpha even though the data comes
after a TBM trailer, which really messes with the decoding.

------------------------------------------------------------------------------------------

So the only thing we need to implement is passing a token chain length plus
offset to the decoder modules, so Core Alpha would get

Token Chain length: 7
Offset: 0

and Beta

Token Chain length: 3
Offset: 7

Can you confirm this?

Yes, this should fix the problem.

------------------------------------------------------------------------------------------

Doug

**Comment by simonspa** [comment]
Hi @drberry85, it actually broke github... :) I found your answers anyway.

What I don't get is where the data gets lost. According to all my tests and my understanding, all data recorded is also delivered to the user code. So maybe there it goes bonkers due to the mixed up ROC id numbering?

**Comment by drberry85** [comment]
Simon,

It could be the case that the pretest and pixel alive test are not written correctly to handle the missing ROCs. Because when I look at the raw data I do see all the ROC headers. I just don't know what the test is doing with the data:
```
[14:36:27.106]     INFO: 10 events found. 10 events expected.
[14:36:27.106]    DEBUG: <PixTest.cc/banner:L1262>    ----------------------------------------------------------------------
[14:36:27.106]    DEBUG: <PixTest.cc/banner:L1263>    Decoding Event Number 0
[14:36:27.106]    DEBUG: <PixTest.cc/banner:L1264>    ----------------------------------------------------------------------
[14:36:27.106]    DEBUG: <PixTestTiming.cc/TimingTest:L470> Event: ====== 0 ====== a004 80b1 4688 4688 4688 4688 4688 4688 4689 e020 c000 a004 80b0 4688 4688 4689 4688 4688 4689 e020 c000 
[14:36:27.106]    DEBUG: <PixTestTiming.cc/TimingTest:L479> 2 TBM Headers found. 2 TBM Headers expected.
[14:36:27.106]    DEBUG: <PixTestTiming.cc/TimingTest:L480> 2 TBM Trailers found. 2 TBM Trailers expected.
[14:36:27.106]    DEBUG: <PixTestTiming.cc/TimingTest:L481> 13 ROC Headers found. 13 ROC Headers expected.
...
[14:36:27.108]    DEBUG: <PixTest.cc/banner:L1262>    ----------------------------------------------------------------------
[14:36:27.108]    DEBUG: <PixTest.cc/banner:L1263>    Decoding Event Number 9
[14:36:27.108]    DEBUG: <PixTest.cc/banner:L1264>    ----------------------------------------------------------------------
[14:36:27.108]    DEBUG: <PixTestTiming.cc/TimingTest:L470> Event: ====== 0 ====== a00d 80c1 4688 4688 4688 4688 4688 4689 4689 e020 c000 a00d 80c0 4688 4688 4689 4688 4688 4689 e020 c000 
[14:36:27.108]    DEBUG: <PixTestTiming.cc/TimingTest:L479> 2 TBM Headers found. 2 TBM Headers expected.
[14:36:27.108]    DEBUG: <PixTestTiming.cc/TimingTest:L480> 2 TBM Trailers found. 2 TBM Trailers expected.
[14:36:27.108]    DEBUG: <PixTestTiming.cc/TimingTest:L481> 13 ROC Headers found. 13 ROC Headers expected.

[14:36:27.108]     INFO: The fraction of properly decoded events is 100.00%: 10/10

```

Doug

**Comment by simonspa** [comment]
I guess it's really the problem of over and over again repacking the data. If you look here https://github.com/psi46/pxar/blob/master/tests/PixTest.cc#L304 the data is read, then the vectors of (wrong) ROC IDs is requested, it iterates over the returned data and packs it into TH2Ds to be returned to the actual test.

With an approach similar to this here we would not need any ROC ids (code not compiled or tested, see as pseudo code):
```
std::vector<pxar::pixel> results;
pxar::statistics mystats;
std::vector<TH2D*> maps;

try {
  results = fApi->getEfficiencyMap(FLAGS, ntrig);
  mystats = fApi->getStatistics();
}
catch(pxarException &/*e*/) {}

fDirectory->cd();

for (unsigned int iroc = 0; iroc < rocIds.size(); ++iroc){
  LOG(logDEBUG) << "Create hist " << Form("%s_C%d", name.c_str(), rocIds[iroc]);
  h2 = bookTH2D(Form("%s_C%d", name.c_str(), rocIds[iroc]), Form("%s_C%d", name.c_str(), rocIds[iroc]), 52, 0., 52., 80, 0., 80.);
  h2->SetMinimum(0.);
  h2->SetDirectory(fDirectory);
  fHistOptions.insert(make_pair(h2, "colz"));
  setTitles(h2, "col", "row");
  maps.push_back(h2);
 }

for(std::vector<pxar::pixel>::iterator pix = results.begin(); pix != results.end(); pix++) {

  // This ROC is yet unknown, book new histogram:
  while(pix->roc() >= maps.size()) {
    TH2D *h2(0);
    h2 = bookTH2D(Form("%s_C%d", name.c_str(), maps.size()), Form("%s_C%d", name.c_str(), maps.size()), 52, 0., 52., 80, 0., 80.);
    h2->SetMinimum(0.);
    h2->SetDirectory(fDirectory);
    fHistOptions.insert(make_pair(h2, "colz"));
    setTitles(h2, "col", "row");
    maps.push_back(h2);
  }

  // Let's add the pixel to the histogram:
  TH2D * h2 = maps.at(pix->roc());
  h2->Fill(pix->column(), pix->row(), static_cast<float>(pix->value()));
}
```

**Comment by simonspa** [comment]
Hi @drberry85 

I have been working on this once more. Now the number of ROCs per TBM channel is configurable. the settings "nrocs"/"nrocs1" for the first channel and "nrocs2" for the second channel of a TBM core have to be supplied via the tbmParameter files, just as an additional setting:

```
nrocs1 4
nrocs2 3
```
would configure one TBM09 core decoder such that it expects 4 ROC headers in data stream 1 and only three in data stream 2.

What I have not yet done is adjusting the ROC header ID returned by the modules. This means that there are still gaps in the counting as soon as a ROC is bypassed somewhere. E.g. TBM08b Core A has 7 ROCs numbered {0..6}, but then the Core B will have 8 ROCs which are labeled {8..15}

I don't have strong opinion on this, but I'd rather keep this scheme since it carries additional information. The actual test code dealing with the data returned from pxarCore can easily be adapted as shown above.

This whole change is backwards compatible, i.e. *not* setting the new parameters will just default to 4 ROCs per stream on TBM09 and 8 ROCs per stream on TBM08.

Be aware that the API will throw an InvalidConfig exception if the total number of supplied ROC DAC vectors and the sum of the token chains of all channels do not agree (i.e. supplying 16 ROC DAC vectors for a module, but bypassing two of them won't work, you would have to supply only 14 DAC vectors then). If this cross-check is too much, we can disable it again.

All the code is together with a major rework of all the decoding pipelines in my repo, branch `tbmemu-new` (sorry for the cryptic name, I was working with the TBM emulator when the need for the decoder changes arose...)

Let me know what you think.

**Comment by xshi** [comment]
Hi Simon and Doug, 

We just build a module which missing the ROC7 (physically not there) and I test it with your branch with FW4.1. Unfortunately it has a segfault:

http://etna.physics.purdue.edu/P-A-2-08/v2/segfault.log

All the related parameters are stored in the above directory, where I the relevant changes are: 
configParameters.dat => nRocs 15 i2c: 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15
tbmParameters_C0a.dat:=> 7       nrocs1  7

Let me know if you have any suggestions. 
Thanks!
Xin

**Comment by drberry85** [comment]
Xin,

That's a problem with how the pretest was written, and not the
deserializer. I would look at:
/home/purduepix/pxar/puhep/tests/PixTestPretest.cc:536
and see what the pretest is trying to do. I highly suspect that the test
was coded up for 16 ROCs only and it tries to access element 16 of a length
15 vector.

Doug

Doug

**Comment by simonspa** [comment]
Hi Xin,

The code seems to crash in

 PixTestPretest::setVthrCompCalDel() () at /home/purduepix/pxar/puhep/tests/PixTestPretest.cc:536

Which has not been touched. Could you check what the problem might be?

Beside that: please use firmware 4.0 until otherwise suggested. pxarCore still references firmware 4.0 even though differences are minor.

/Simon

Am 14. Mai 2015 22:41:13 MESZ, schrieb Xin Shi <notifications@github.com>:

**Comment by simonspa** [comment]
@drberry85 sorry, saw your comment too late. you already wrote what I intended to say...

**Comment by xshi** [comment]
HI @simonspa  and @drberry85 ,

Thanks for your reply. I have tried to skip the ROC7 in the loop, but still get crash. From my observation, the programROC worked fine, which has the same rocs loop as the setVthrCompCalDel, I don't know why that makes the difference... 

Xin

**Comment by simonspa** [comment]
@xshi see my comment above with the code example. I really think that this is the culprit and that the code could/should be made smarter to circumvent (or rather: to not create) these problems.

**Comment by aehart** [comment]
Hi @simonspa,

You mentioned there are gaps in the counting when ROCs are bypassed, but you could also have the opposite problem where multiple ROCs are assigned the same ID. For example with a TBM08b, if a ROC on core B were bypassed, then the last ROC on core A and the first ROC on core B would have the same ID (7) because of this line:
https://github.com/psi46/pxar/blob/tbmemu-new/core/decoder/datapipe.cc#L254

I've added a function for keeping track of the number of ROCs in the preceding TBM streams so there are no gaps or overlaps in the counting. That's in the OSU fork here:
https://github.com/OSU-CMS/pxar/tree/tbmemu-new
I can do a pull request if you think the changes are reasonable. An alternative would be to keep the gaps by using the normal token chain length instead of the length for the current channel.

Note that this has nothing to do with the other problems I see with the two modules here, like not seeing any data coming from certain non-bypassed ROCs. But at least the data is getting assigned to the correct ROCs now.

Cheers,
Andrew

**Comment by simonspa** [comment]
Hi @aehart 
you are fully right here, I have totally missed that I was shifting just by the (back then fixed) token chain length.

I guess I would be in favour for not mingling the data streams but rather use a fixed tokenchain spacing according to the TBM used. That would result in gaps in the numbering but would keep all data streams completely independent - even though your solution with passing the full tokenchain vector is a nice way to implement this. What's your opinion?

Concerning the missing data:
you are really missing the data in the raw data stream from the DESER400? Have you tried to run pxarCore with the python cli on DEBUGPIPES verbosity and trying something like

```
daqStart
daqTrigger 10 500
daqGetEvent
[....]
```

and check the output? If the data is misssing there (check the "full raw data blob" printout) then we really have a problem further upstream in the DTB. Otherwise we can check how far it gets (do we screw up decoding?) or if it's really lost on test level.

Cheers,
Simon

**Comment by aehart** [comment]
Probably somebody with more experience with the tests should weigh in on which approach is preferable. I guess one advantage of not having gaps in the ROC IDs is that the tests are more likely to work out of the box since the number of ROCs and the number of IDs would continue to be identical.

As for the missing data, I haven't ever run the Python tool and am having some problems running it. But I've run pxar with the DEBUGPIPES flag, and parsed the raw data blobs with a little Perl script.

For the M_RR_913 module (ROCs 2, 10, 13 bypassed, [log file found here](http://cmshead.mps.ohio-state.edu/~hart/M_RR_913.log.gz)), I see 7 ROC headers from TBM A and 6 ROC headers from TBM B in every event as there should be. But there is never any pixel data from ROCs 3, 7, 11, 12, and 15 (I use the I2C addresses for clarity). And the value for the data from ROC 1 is always zero. So maybe there is something wrong with how DESER400 is handling the data.

For the M_FR_906 module (ROCs 1, 7, 11, 12, 13, 14 bypassed, [log file found here](http://cmshead.mps.ohio-state.edu/~hart/M_FR_906.log.gz)), the first ROC header from TBM A and the last ROC header from TBM B are always messed up, leading to events like:
a002 8000 07f0 41c8 41c8 41c8 41c8 41c9 e022 c000
and
a001 80c1 41c8 41c8 41c8 07f1 e062 c080
This results in a lot of errors like "Number of ROCs (3) != Token Chain Length (4)" for both TBM cores. So maybe the TBM on this module is bad in some way.

Cheers,
Andrew

**Comment by drberry85** [comment]
Andrew,

'But there is never any pixel data from ROCs 3, 7, 11, 12, and 15 (I use the I2C addresses for clarity)'
I highly suspect the delays are set to the wrong values from the pretest. If your caldel is wrong for your ROC then you will miss all your pixel hits. Try doing a dacdac scan in vthrcomp and caldel, and then assign the caldel manually per ROC... which is a pain.

For M_FR_906, when you see events with improperly formatted ROC headers (07f0 or 07f1), just ignore the event. There is a decoding issue, so either the delays are not set correctly on TBM or the ROC delay chain. I would highly suspect that this problem is intermittent. E.g. you see it some days and not others, but I don't know the cause. I would focus most of your time on M_RR_913, and not worry about the decoding issues on M_FR_906, unless you're really interested in them.

Doug

**Comment by simonspa** [comment]
Thinking a bit more about this I tend to still like the fixed token chain length better, mostly because it carries more information. One can still trace back from which TBM channel each ROC has been read out - which might be an interesting information in case one of the channels had a bad timing or so.

However, I leave this completely to you FPIX guys since up till now you are the only ones I know of with bypassed ROCs...
Just let me know what would be your preference, I have PR #342 dangling until we solved this issue.

**Comment by xshi** [comment]
Hi all, 

Thanks for all of your comments. I just tried @aehart branch and so far it can run the pretest.  (the rocs numbers goes from 0 to 14 as expected). 
http://etna.physics.purdue.edu/P-A-2-08/v2/pretest.png 

When I run the PixelAlve test, it shows 

[16:57:31.387]    ERROR: <api.cc/repackMapData:L1749> This pixel doesn't belong here: ROC 4 [44,32,2].
http://etna.physics.purdue.edu/P-A-2-08/v2/alive.png
http://etna.physics.purdue.edu/P-A-2-08/v2/alive.log

Any ideas? 

Xin

**Comment by aehart** [comment]
Since no FPIX people have expressed a strong opinion about the ROC ID thing, I think we should go with the consecutive numbering implemented in my fork. All the tests seem to work with no modification, whereas some of them segfault when there are gaps in the numbering. I've also added a couple other simple things like writing the nrocs parameters when the TBM config files are written.

As for the error Xin saw in the PixelAlive test, I do not see it with the M_RR_913 module at OSU. There is still some timing problem there, where some of the ROC headers get corrupted. This happens maybe 1 in 3 times that it's been tested. The other module we have has a similar problem 100% of the times it's been tested.

Maybe it makes sense to merge PR #342 along with my few additions now, and consider the remaining timing problems as a separate issue?

Cheers,
Andrew

**Comment by simonspa** [comment]
Hi @aehart, I agree with your suggestion, let's go ahead then. Do you file a PR against my repository with the changes you need so all the things end up in #342?
Then I will merge #342 or ask @ursl to review and merge.

**Comment by simonspa** [comment]
This issue should be solved with @aehart's commits.
