### ISSUE TITLE
Timing test:  Not Working until after a good value for Delay Regestars Found?

### ISSUE THREAD

**Issue by jking79** [psi46/pxar#280]
While running test for N00601 and MFR913; both TBM08a, ROC v2, HDI Rev C modules; I was unable to get results from the timing test, or any other test, until after we utilized psi46test to find values, via trial and error, to set the delay registrars to.  After these values where found then the timing test was able to "fine tuned" the settings.

Has anyone else found it necassary to do this?  Is this expected?  If it is expected then is it neccessary to do the timing test?

**Comment by vtavolar** [comment]
Hello,

we have similar experience at ETH. 
Module D0008, TBM08b, ROC v2.1respin. Timing test took quite long (24 mins) and didn't provide optimal values. We can operate one ROC at the time, while, before the Timing test, even this was not successful. We also don't get results for any other test, due to missing events in the readout.

I use pxar version 92dfca83a810208101304f1199f37f45a4a9a259, FW 3.6, Linux Red Hat 6.5.

We were able to operate the same module at PSI after a (much faster) Timing test.

**Comment by vtavolar** [comment]
Increasing vdig to 10 helped a lot in my case. I am now able to have results for all 16 ROCs. Nevertheless, this doesn't seem to be the only factor involved: the same settings don't work anymore for me if a different DTB is used.

**Comment by simonspa** [comment]
There is a reworked timing test. Please run that and open a new ticket in case you experience problems.
