### ISSUE TITLE
Create new X-Ray spectrum plot after source changes

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#292]
Hi,

it would be handy in in Xray : phrun if a new histogram for the spectrum would be generated, if the value of the parameter "source" has changed instead of adding the new values to the old histogram belonging to a different source.

**Comment by jking79** [comment]
Also,
It is my understanding that MoReWeb does fits for the xray spectrum.  Would this be possible to add to the pxar xray test?
Jack 

     On Friday, February 6, 2015 8:02 AM, piberger <notifications@github.com> wrote:
   

 Hi,it would be handy in in Xray : phrun if a new histogram for the spectrum would be generated, if the value of the parameter "source" has changed instead of adding the new values to the old histogram belonging to a different source.—

**Comment by ursl** [comment]
Hi Pirmin, 

please try 9e15ee35c9243fa18c8a3adc56018c52251f17bc. 

Jack: the fitting will come. 

Cheers,
--U.

**Comment by piberger** [comment]
Thanks, working as expected now when changing the source.
