### ISSUE TITLE
Pulse height optimisation and x-ray spectrum

### ISSUE THREAD

**Issue by thweiler** [psi46/pxar#326]
We see a strange behaviour in the x-ray spectrum which is probably related to the pulse height optimisation. Measuring the spectrum of a Ag after running a full test, the resulting distribution 
looks not that nice (see attached plots), repeating the PhOptimisation and GainPedestal test on the already optimsied dacParameter files (pXar -d .... -T 35 -g) improves the spectrum then looks and the peak is at the expected Vcal value (compared to what we got with earlier pXar versions).
The plots were generated with pXar 1.8.4 (commits ~April 6th - April 10th).

full module:
![m4507-fulltest-phoptgainped-mo](https://cloud.githubusercontent.com/assets/7323782/7115145/7ba18a00-e1e5-11e4-8b45-ffe2ea034413.png)
single chip assembly:
![m0307-fulltest-phoptgainped-ag](https://cloud.githubusercontent.com/assets/7323782/7115154/9243e528-e1e5-11e4-83d9-c66e387d1722.png)

**Comment by ursl** [comment]
Hi Thomas,

can you please provide a logfile (including the initialization lines)?

Thanks.

Cheers,
--U.

**Comment by thweiler** [comment]
Hi Urs
I copied the log files to my webspace:
http://ikcms02.fzk.de/weiler/pXar/
fulltest.log  // first full test with parameter generate with mkConfig
Spectrum_Ag-6mA-run005-wo2pHOptGainPed-Mask4.log // Xray test after full test, several pixels were masked
pHOptGainPed2-woMask.log // repeat phOptimsation and GainPedestal, dtarting on parameters received from first fulltest (option -T 35)
Spectrum_Ag-6mA-run008-w2pHOptGainPed-Mask5.log // xRay test on reoptimised parameters

pXar was run for the fulltest like:  cat main/test | ../bin/pXar -d ~/pXar_output/...
repeating phOpt, gainpedestal and Xray Test like: ../bin/pXar -d ... -T 35 -g

cheers
Thomas

**Comment by ursl** [comment]
Thanks. It's not obviously clear to me that the fulltest version is fitting
with the correct version. I'll check.

Cheers,
--U.

**Comment by thweiler** [comment]
Hi Urs,
Just for completeness, when we do "full test" via the gui, run each test in its own tab, 
the result looks the same, see attached plot.
cheers
Thomas

![m4513_agcomparision](https://cloud.githubusercontent.com/assets/7323782/7153818/ee6d1d5e-e34f-11e4-8396-617a5fb00577.png)

**Comment by ursl** [comment]
Hi Thomas,

thanks. I have  question: Did you re-run the PH optimization test because
re-running only the gain-ped test would not cure the problem, or did you
rerun the  PH optimization test "just so" (I mean it can be considered
natural to do so, but maybe you had a specific reason)? I am not asking to
rerun anything, just whether there was a specific reason.

Cheers,
--U.

**Comment by thweiler** [comment]
Hi Urs,
In principle it was just a try since we grounded our cooling plate to reduce the number of noisy pixels and improve the spectrum. To avoid repeating the full test again we just did phOptimization and GainPedestal (why we run both I am not sure, maybe had a look at Vcal dacscan). So the grounding seemed to work for us, but when did with the newly grounded setup a full test from scratch, the quality of the spectrum was worse again and a second run of phOptimzation and GainPedestal cured the problem.
cheers
Thomas

**Comment by ursl** [comment]
Hi Thomas, 

this was an artefact of (now) using in the gain/pedestal calibration the same function name as in the scurves (run before in the fulltest). The function was then "recycled", however with very wrong x-axis range. 

When not running a fulltest, in particular not running scurves before the gain/pedestal calibration, this would not be an issue as the function would not yet exist. 

This should be fixed with the HEAD (mandatory f/w 4.0 now), at least in my test. Please reopen if you still observe problems. 

Thanks for spotting this. 

Cheers,
--U.
