### ISSUE TITLE
More robust USB communication needed?

### ISSUE THREAD

**Issue by xerxes1986** [psi46/pxar#327]
Hi,

During parallel module testing via elComandante we noticed issues with pXar and sending commands to start tests. We had to induce delays between subsequent testboards in order for them to work at all, and we think the issue lies with a hangup in the USB communications. We think it has something to do with the PC sending a command to a testboard and then assuming that command got thru.

I suggest adding in some sort of framework where the testboard itself will communicate and verify with the PC that it has received a command. It would look something like this:

PC Sends Command To Start Test A -> Testboard Tells PC "I got command to start test A, starting now" -> If PC doesn't get this "acknowledgement", it tries again

We think this would ensure the testing software is more robust against USB timeout and connection issues. A similar setup could be used to verify that data sent from the testboard is received by the PC using some sort of checksum verification.

**Comment by ursl** [comment]
Hi all,

did anybody else have similar issues?

What OS/distribution/USB-version/FTDI-drivers are you using, Paul?

Cheers,
--U.

**Comment by xerxes1986** [comment]
Hi,

We observed this on the teststands at FNAL. I believe these are running Ubuntu 12.04LTS with the latest drivers, but would have to check. I’ll ask Jaime if he can post the specifics.

-Paul

**Comment by lantone** [comment]
Hi Urs,

Here's what I found:

Ubuntu 12.04.5
USB version 2.0
FTDI version 1.1.12

Cheers,
Jamie

**Comment by piberger** [comment]
Hi,
last week I had issues with one of the testboards. When starting the test os sometimes randomly after a few minutes it stopped communication to the PC and pxar throwed libFTDI USB communication errors. This testboard was working before but seems to be broken since last week. 
I don't know if this is related to the same issue you have mentioned, but because of this experience I would try to substitute the testboards if you haven't done so.

Besides that one sometimes failing testboard, I did a lot of long tests with 4 testboards in parallel and did not see any USB errors.

Cheers,
Pirmin
