### ISSUE TITLE
Windows build failing

### ISSUE THREAD

**Issue by sheindl** [psi46/pxar#328]
Dear all,
we are trying to build the latest pXar version (for fw 4.0) under Windows for our probestation. Unfortunately the build fails with a very cryptic error message. The warnings can be ignored since they are all about conversions.
I apologize for the German errors but it seems like there is no option in Visual Studio to set the language (at least according to Google).

Stefan

````
"D:\psi46test\pxar\build\INSTALL.vcxproj" (Standardziel) (1) ->
"D:\psi46test\pxar\build\ALL_BUILD.vcxproj" (Standardziel) (2) ->
"D:\psi46test\pxar\build\main\pXarW32.vcxproj" (Standardziel) (4) ->
"D:\psi46test\pxar\build\gui\pxargui.vcxproj" (Standardziel) (7) ->
"D:\psi46test\pxar\build\tests\pxartests.vcxproj" (Standardziel) (8) ->(Link Ziel) ->
  PixTestTiming.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol ""class pxar::statistics & __cdecl pxar::operator+=(class pxar::statistics &,class pxar::statistics const &)" (?Ypxar@@YAAAVstatistics@0@AAV10@ABV10@@Z)"
in Funktion "__catch$?getEvents@PixTestTiming@@QAE?AVstatistics@pxar@@HHH@Z$2"[D:\psi46test\pxar\build\tests\pxartests.vcxproj]
  D:\psi46test\pxar\build\tests\Release\pxartests.dll : fatal error LNK1120: 1 nicht aufgeloeste Externe [D:\psi46test\pxar\build\tests\pxartests.vcxproj]

    60 Warnung(en)
    2 Fehler
````

**Comment by simonspa** [comment]
Sorry for asking the obvious, but did you run this in a clean build directory>

If yes, to me it looks like there is a problem finding the `pxar::statistics` definition (which lives in core/api/datatypes.h). The `DLLEXPORT` tag has not been forgotten in the class definition, so that's not the problem. Since the same file also hosts the definitions for e.g. `pxar::pixel` it's unlikely that all is missing.

**Comment by sheindl** [comment]
Hi Simon.
Yes, I did git pull, removed all files in build, cmake .., MSBUILD and I repeated the same procedure just now. Still the same problem.

**Comment by ursl** [comment]
Does the problem not lie in 

   friend statistics& operator+=(statistics &lhs, const statistics &rhs);

instead of the statistics definition?

I don't know about your error counting (is your text above containing already both errors or is there another one?). Did PixTestPretest compile fine (that is also using explicitely statistics, though not in the header file)?  Maybe add a forward declaration?

**Comment by simonspa** [comment]
Maybe add an additional `include "datatypes.h"` in `PixtestTiming.cc`?

**Comment by sheindl** [comment]
I will try Simon's approach as soon as I'm back at KIT. I don't have a Windows machine at the DESY testbeam. Or perhaps @bojanh wants to try? ;-)

**Comment by bojanh** [comment]
Hello,

I tested the Simon-Stefan approach with additional `#include "datatypes.h"`, but I still get the same error that Stefan posted above.

**Comment by sheindl** [comment]
Hi Simon.
After a long time I reinvestigated the Windows build problem and it seems like I have found the solution. At least it makes pXar compile under Windows but the fix still needs to be tested under Linux.
Could you just try it under Linux and, if it works there also, commit to master?

The solution is to remove the definition of
``statistics& operator+=(statistics &lhs, const statistics &rhs)``
completely from datatypes.cc (lines 180 to 210) and instead add it to datatypes.h after line 467,
like you do with all the other overloaded operators in datatypes.h.

Cheers, Stefan
