### ISSUE TITLE
Readout problems with FW4.0 and single ROCs

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#333]
Hello,

i tested a single ROC with Pretest and Setup test done and trimmed to 40 under two conditions:
A) FW3.6, pxar commit f460b23 (2nd of april 2015)
B) FW4.0, pxar commit dfeed40 (22nd of april 2015)

A) shows no problem, where as with B) PixelAlive test produces bad results:

![pixel_alive_fw40](https://cloud.githubusercontent.com/assets/10864232/7374634/b4ffbd18-edd3-11e4-8b95-f5ab7ce57b49.png)

together with a lot of read out errors:
````
[17:23:51.453]    DEBUG: <PixTest.cc/efficiencyMaps:L369>       attempt #0
[17:23:52.217]    ERROR: <datapipe.cc/CheckEventValidity:L420> Number of ROCs (0) != Token Chain Length (1)
[17:23:52.217]  WARNING: ROC 0: Readback start marker after 15 readouts!
[17:23:52.217]    ERROR: <datapipe.cc/CheckEventValidity:L420> Number of ROCs (0) != Token Chain Length (1)
````
as long as vdig is kept at its default value "6". After raising vdig to "9", the problems disappear. Running setup test again does not solve the problem.
Other DACs:
![hw_tab_fw36](https://cloud.githubusercontent.com/assets/10864232/7374643/be633ca4-edd3-11e4-9460-fc4da9ad8938.png)
Setup test:
![setup_fw40](https://cloud.githubusercontent.com/assets/10864232/7374823/c29e72a6-edd4-11e4-8958-d8cfd5f55ddb.png)
The setup test takes longer than usual for step 17:
````
[18:29:28.922]     INFO: 16:  ffc     ffc     ffc     fcc     efc     ff0     f1c     1fc    
[18:29:28.947]     INFO: 17:  f1c     ffc     ffc     fec     efc     ff0     f0c     0fc    
[18:29:45.834]     INFO: 18:  f0c     ffc     ffc     ffc     ffc     ffc     ffc     ffc    
[18:29:45.856]     INFO: 19:  ffc     ffc     ffc     ffc     ffc     ffc     ffc     ffc  
````

Without trimming, PixelAlive map looks good. During the Trim test itself a lot of read out errors occur.

I never had these problems with modules, does anyone observe the same for single ROCs or knows any solution to this?

**Comment by simonspa** [comment]
Hi @piberger 

do you still have these problems, also if you exchange the DTB for another one? You are the first person since a year or so having problems with single ROC readout.

However, we at DESY have for example one board where the token_out from the chip is not correctly detected and this many events are lost or garbage.

Do you only see this with one DTB or also with others? Might it be the ROC itself that is flaky?

Cheers,
/Simon

**Comment by thweiler** [comment]
Hi
I tested some respin singles and a full module (TBM08b and respin ROCs) with fw4.0 and had a lot of errors like:
ERROR: <datapipe.cc/CheckEventValidity:L420> Number of ROCs (0) != Token Chain Length (1) 
as reported by piberger. Using another DTB did not improve the situation.
Going back to FW3.6 solved this issue, just the warning:
WARNING: ROC 0: Readback start marker after 15 readouts!
appeared from time to time.

Cheers
Thomas

**Comment by simonspa** [comment]
Did you by any chance rerun the setup test to adapt your DTB timing?

**Comment by piberger** [comment]
Hi @simonspa ,
I tried different ROCs with different DTBs and adapters and always had the same problem during and after trimming, at 17 degrees and at room temperature (around 25 degrees).
A semester student also had the same problem, but reported they were gone when testing the ROC at -20 degrees. I didn't check this yet but will do it and also check if the the problem still exists with the latest pxar version.

**Comment by simonspa** [comment]
I'm pretty sure that this can't be a software issue - especially if it changes with temperature. At software level we don't see any electrical signals anymore which could change with temperature - it hast to be in the DTB, at the deserializer or further upstream. Please make sure that your DTB delays (clk, ctr, tin, sda and the DESER160 phase setting) are correct for the firmware and testboard selected. Rerun the setup test when in doubt.

**Comment by thweiler** [comment]
Hello Simon
For the  singles I always did a setup/pretest/fulltest when chaning the between the firmawares. The problem is that the frequency and appearance of these errors/warnings is not always 
reproducible. Sometimes it happens first at Pretest or the BumpBonding test, ....
Did the reporting on these Errors/Warning changed between  FW3.6/FW4.0 and the corresonding 
pxar versions?
Cheers
Thomas

**Comment by simonspa** [comment]
Yes, the check for missing ROC headers in the DESER160 data stream has just been added in https://github.com/psi46/pxar/commit/c8dda96e8c6558a8c321adb6426d6b4cd57910d2 - which is already well into the FW4.0 era.

Good idea to check this, thanks!

**Comment by simonspa** [comment]
To conclude: the problem most likely was there before, but the check for it in the decoder modules was not present yet.

I'm not sure how to go about this since having a non-working single ROC setup is clearly not acceptable for @piberger. I would really guess it's still a timing issues.

Could you record some data and just dump the raw data somewhere to look at?
e.g. run the python CLI and do:

```
# Startup:
./python/cmdline.sh -d our/cfg/files
# Start the DAQ
> daqStart
# Send some 2k triggers, spaced by 5k BC:
> daqTrigger 2000 5000
# Get the undecoded raw data buffer from the DTB and dump it:
> daq GetBuffer
```

**Comment by piberger** [comment]
I could not reproduce the problem anymore with the current setup. I will close the issue at it was probably not caused by pxar but either DTB or other problems in the setup as pointed out above (noise maybe?).
Thanks for your help!

**Comment by simonspa** [comment]
Yeah, I managed to reproduce this today by taking a chip with sensor bonded, no HV applied and a vthrcomp of 100 - some pixels are noisy and thus garble the readout.

Thanks for closing.
