### ISSUE TITLE
BUG with getDeviceList for finding connected DTBs when Coldbox is attached

### ISSUE THREAD

**Issue by xerxes1986** [psi46/pxar#350]
I have found a bug in pXar that prevents it from finding a list of connected DTBs when there is a coldbox connected to the PC with incorrect permissions. This only appears when the coldbox is connected to the PC and the permissions on its device are not set to readable by pXar. It appears that pXar attempts to scan the connected USB devices and find ones that match "DTB_" in the name, but when it comes upon a device it cannot read it crashes out instead of continuing to the next device in the list.

The example output is:
[15:38:41.741]     INFO: Log level: DEBUG
libusb couldn't open USB device /dev/bus/usb/003/005: Permission denied.
libusb requires write access to USB device nodes.
[15:38:41.743] CRITICAL: <rpc_calls.h/GetDeviceList:L196> 
[15:38:41.743] CRITICAL: <rpc_calls.h/GetDeviceList:L196> 
[15:38:41.743] CRITICAL: <hal.cc/FindDTB:L391> Could not find any connected DTB.

This should be fixed in pXar, but is also fixed if a udev rule is created for the coldbox that gives it the right permissions:

ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", GROUP="usb", MODE="0664", SYMLINK+="ttyUSBColdbox"

**Comment by simonspa** [comment]
Dear @xerxes1986, I tried to reproduce this behaviour with other USB devices but there everything seems to work properly. From what I can see in your udev rule, the cold box also features an FTDI chip (same vendor ID as the DTB) and that might cause the problems.

However, I'm not sure how we can go about this since we are using the `FT_ListDevices()` functions by the vendor's libftd2xx library to get a list of all attached FTDI devices and select the correct ones. If this library happens to return nothing in case one FTDI device does not have write access enabled I fear we can't really do anything about this.

The lines in question are located in `core/usb/USBInterface.libftd2xx.cc`:
https://github.com/psi46/pxar/blob/master/core/usb/USBInterface.libftd2xx.cc#L81

Just for the sake of completeness, could you do the following things for me?

 * re-run the above with the DEBUGRPC verbosity level, maybe that gets us some more information.
 * check (without your udev rule) if the same thing happens if you compile with `cmake -DUSE_FTD2XX=OFF ..`? This switches to the open source libftdi instead (which of course needs to be installed)

**Comment by simonspa** [comment]
Any news on this?

**Comment by simonspa** [comment]
Hi @xerxes1986 
since I haven't heard anything back concerning this issue, and it's not a pxar issue after all I will close this ticket. The problem you are facing is due to an improper configuration of your system. If all FTDI devices are covered by your UDev rule, and are set to mode 0664 and made accessible to all users of the group "usb" there should not be a problem in operating the ColdBox and several DTBs on the same machine.

Cheers,
Simon

**Comment by drberry85** [comment]
Simon,

Paul (@xerxes1986 <https://github.com/xerxes1986>) graduate back in spring
and he just left for a new position in Idaho. I don't know if this issue is
completely resolved on our tests stands. I'll have to check with @jstupak
<https://github.com/jstupak>.

Doug

**Comment by drberry85** [comment]
Simon,

It looks like Paul fixed the udev rules and we haven't had an issue since,
so I think this ticket can stay closed.

Doug

**Comment by simonspa** [comment]
Even better... :)

Am 25. August 2015 19:55:15 MESZ, schrieb Doug Berry <notifications@github.com>:
