### ISSUE TITLE
Pixel masking not working (single ROC)

### ISSUE THREAD

**Issue by drberry85** [psi46/pxar#354]
Simon and Urs,

For phase 2, we would like to run on a single ROC with many of the pixels masked. However, whenever we add pixels to defaultMaskFile.dat, the pixels are not masked in the actual tests (pixel alive, trim... etc). I believe the problem is that most test call something like this:
```
  fApi->_dut->testAllPixels(true);
  fApi->_dut->maskAllPixels(false);
```
Which sets all the pixels to active and disables all the masking. Is there a way we can change the API such that it remembers to leave the pixels in the defaultMaskFile masked? Or maybe add another method to the API which knows to leave the pixels in defaultMaskFile masked.

Doug

**Comment by drberry85** [comment]
As Urs pointed out. The pixel masking is working as designed. This is a feature request for pXar to be able to permanently mask certain pixels (and not unmask them for tests). This is desired for a phase two signal ROC that has three different PUC designs.

Doug

**Comment by ursl** [comment]
Hi all, 

in the end I did implement your request with the defaultMaskFile.dat. My implementation is very similar to what Jamie had in the OSU repository, but I changed a bit the underlying s/w (to avoid reading in the file all the time). Since I had to touch every test anyway I also inserted a function call at the end of each (sub)test that leaves the DUT in the same state. Also from Jamie is a modification to the trim test that should positively affect also ROCs without masked pixels. 

From my testing this setup is substantially slower than without masked pixels, but this is expected (as some serialization will occur). 

If somebody observes problems, please open again. 

Cheers,
--U.
