### ISSUE TITLE
remove hard coded parameter from Scurves?

### ISSUE THREAD

**Issue by jstupak** [psi46/pxar#359]
Can we remove the hard coded parameters here:
https://github.com/psi46/pxar/blob/master/tests/PixTestScurves.cc#L188-L193
and take them from the config file instead?

I would like to override the default parameters via the config file, or something like:
https://github.com/jstupak/pxar/blob/FPIXTestUpdate/usertests/PixTestFPIXTest.cc#L108-L113
But this doesn't work with the current version of PixTestScurves::fullTest.

Or is there some other way to achieve my goal?  Thanks!

**Comment by ursl** [comment]
Why don't you invoke in your PixTestFPIXTest PixTestScurves::doTest
instead? The ::fullTest method should stay fixed, preferably. Since
you have your own fulltest, you can invoke whatever you like there
(putting the doTest call into the if statement already present and
treating the other test calls in the else clause).

Cheers,
--U.

**Comment by jstupak** [comment]
Thanks Urs.  I didn't realize this was the distinction you were going for between doTest and FullTest.  Your suggestion should be fine.
