### ISSUE TITLE
rocID for sparse ROC selection and single pixel running

### ISSUE THREAD

**Issue by ursl** [psi46/pxar#365]
Hi Simon, 

we wonder about https://github.com/psi46/pxar/blob/master/core/api/api.cc#L1600

We (mostly Martin Lickteig, and then in disbelieve also I) noticed that the trim algorithm does not really work if 0 .. n ROCs are deselected, and only n+1 ... are selected. The symptom is that the call in 

https://github.com/psi46/pxar/blob/master/tests/PixTestTrim.cc#L259

will result in 

[17:19:32.218] CRITICAL: <api.cc/expandLoop:L1640> NO DATA FROM TEST FUNCTION -- are any TBMs/ROCs/PIXs enabled?!

But there ARE Rocs enabled, for instance 13 and 15. All the other api calls work, but this call is special because it is one different pixel per ROC. 

It seems that the line above will result in ROCs 0, ... being polled for the enabled pixels, while for instance calling 

    fApi->_dut->testPixel(ix, iy, true, rocid);
    fApi->_dut->maskPixel(ix, iy, false, rocid);

will result in setting ROCs n+1, ... (as expected, I think).

Martin would think that 

	std::vector<pixelConfig> enabledPixels = _dut->getEnabledPixels(rocit->i2c_address);

does the right thing. From our simple test it indeed looks like it's OK. 

Cheers,
Martin+
--U

**Comment by simonspa** [comment]
Hm, no, Martin's thought is not correct as is, since looking at the DUT function `getEnabledPixels(id)` is does not check the I2C address of the ROC config but the ROC's position in the ROC vector (aka its ID)
It probably works since usually the I2C addresses are aligned with the ROC id on normal modules.

However, there is a problem in that part of the code, indeed: the iterator only iterates over *enable* ROCs making it jump around in the ROC vector, so Martin's idea of using the I2C address is much better. I think I fixed this with my last commit to master - please confirm...

**Comment by ursl** [comment]
for me it works indeed now. 

Thanks, 
--U.
