### ISSUE TITLE
Mark commits that require re-generation of config files

### ISSUE THREAD

**Issue by vtavolar** [psi46/pxar#378]
Hi,

I would ask that whenever a commit introduces changes in the code that require the config files to be updated for the fulltest to work properly, that commit would be flagged clearly, maybe in the commit message. This request is triggered by the example of the recent changes in the GainPedestal tests introduced in 33e44d0658bac01b284a9b286783bd01a2e3d5aa which make the fulltest fail if no vcalstep variable is declared in testParameters.dat.

Thanks,
Vittorio

**Comment by simonspa** [comment]
I oppose this and would ask for even more: all changes and new parameters introduced to tests should default to the previous behavior. I.e. if the parameter is not present in the config file the test behaves as it did before.

This backwards compatibility is crucial in my opinion since we are in the middle of production and qualification.

**Comment by ursl** [comment]
Hi all,

I am not sure I agree. I also do not really like Doug's fix to the
problem (though it is technically correct).

Initializing in the c'tor all test parameters to unphysical values has
the advantage that all default configuration comes from ONE place,
testParameters.dat. This (imvho) greatly simplifies things and
minimizes surprises. It is also true that this unphysical
initialization is not applied everywhere (but that does not invalidate
the argument, it rather motivates to change those "faulty"
initializations).

The real problem, again imvho, is that we have not yet defined a tag
for production testing. Jack once asked about it, but since then
nobody raised this issue again. I have been reluctant to tag so far
because of

- minor uneasiness about the trimming test
- missing readback test in fulltest
- hope that the scurves issue might be resolved

Neither of the above is a real show-stopper. Ignoring #1, adding #2.
and ignoring #3 a tag can be produced very quickly, and it would be a
working tag.

BTW, "middle of production" must be weighted with something, and my
guess would be that it is not "number of modules to be produced".

Cheers,
--U.

**Comment by rslu** [comment]
I agree that we need a semi-stable version of production tag and not rely on head that has frequent update. Our cold-box test yesterday all failed and we wasted 8 hours due to this GainPedestal issue and we have to redo them again today.

**Comment by simonspa** [comment]
"Middle" in that context indeed was not meant add "center"... :)

The problem with the unphysical values is, that the tests do not check for unphysical values, but cast them to some fixed size integers (where they might become physical, but huge) and pass them to pxarCore.

Also see #158 for this.

I guess either of the options should be chosen and implemented coherently:
* default to sane values in the code which are then overwritten by testParameters.DAT
* assign unphysical values by default but check them before passing them to pxarCore, throw an exception or similar if a variable is missing

Am 23. Juli 2015 07:40:57 MESZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by ursl** [comment]
Hi all, 

I would propose to use tag prod-03 for module production testing. I would furthermore propose that there would be only bugfixes or very widely requested feature updates to that. 

Regarding the changed testParameters.dat: mkConfig has now a new switch -s which writes only the testParameters.dat and moreTestParameters.dat files and leaves the rest untouched. 

Cheers,
--U.
