### ISSUE TITLE
mask dead pixels through out full test

### ISSUE THREAD

**Issue by rslu** [psi46/pxar#384]
Should we mask all dead pixels through out all tests during fullQualification?
I see all plots using 4160 pixels but if there are dead pixels, they create entries
outside of bulk distribution thus generate large "width".
In my opinion, this double count the dead pixels effect and blow up the later test
such as vcal threshold width or gain width. 
Those plots should only consider alive pixel entries.

Rong-Shyang

**Comment by ursl** [comment]
Hi Rong-Shyang,

the analysis (moreweb) should correct for this, imho.

I think it would be impractical to mask them with defaultMaskFile.dat
because then you'll have different configurations for different ROCs which
will serialize the tests over the ROCs. The result would be (1) surely a
much increased time consumption for the fulltests and (2) likely memory
issues.

Cheers,
--U.

**Comment by rslu** [comment]
Thanks. I agree if it can be done in MoreWeb, it's fine.
I submitted the issue on MoreWeb side.
