### ISSUE TITLE
possible typo in PhOptimization

### ISSUE THREAD

**Issue by lantone** [psi46/pxar#391]
Hi,

    I've been looking through PixTestPhOptimization.cc and I'm confused about this line:
       
        https://github.com/psi46/pxar/blob/master/tests/PixTestPhOptimization.cc#L979

    Is there a typo in here somewhere?  I *think* it's trying to isolate bins within a certain range of maxPH?  Right now it's choosing bins where 0 < maxPH - BIN_CONTENT <= 3, but it seems over-engineered if that was the real intent.  I don't think it's affecting the outcome of the test, I just thought I'd bring it up in case it's an easy fix or in case it's correct and I can improve my understanding.

Thanks,

Jamie

**Comment by vtavolar** [comment]
Hi Jamie,

sorry for this late reply. The intent of that line is exactly what you mentioned. The condition would ideally be maxPH - BIN_CONTENT == 1, but in order to select a wider band of bins (and thus have a larger overlap when choosing the solution) this is relaxed to >0 && <=3. The code might be a bit convoluted here, but I don't think there is a typo. If you have any suggestion on how to improve it I am happy to hear it and implement it.

Bests,
Vittorio

**Comment by lantone** [comment]
Hi Vittorio,
    No worries, thanks for your reply.  I think it makes sense to me now, thanks for explaining.  My only suggestion would be to maybe add a comment explaining the choice of cut.

  One other suggestion (feel free to ignore).  What about filling the th2_sol histograms as follows: 
      0 for points not chosen in hmin or hmax
      1 for points chosen by one but not the other
      2 for points chosen by both hmin and hmax
  The result would be two green bands whose intersection is red.  It might be more illustrative as to the algorithm used for choosing phOffset and phScale.  It should be simple to implement, I could do it if you wanted.  But like I said, just a suggestion, feel free to ignore and close the issue.

Thanks,
Jamie
