### ISSUE TITLE
specify position of gui window

### ISSUE THREAD

**Issue by lantone** [psi46/pxar#430]
Hi,

Is it possible to specify where on screen the pXar gui window will show up? E.g. the top right corner of my screen as opposed to the top left?

Thanks,
Jamie

**Comment by ursl** [comment]
Hi Jamie,

this has been a sore point, I agree.

Please try the master's head. You can
(1) manually modify in configParameters.dat the parameters guiX and
guiY (assuming you run a fresh mkConfig)
(2) startup pXar with -x 1300 -y 0

The latter will dump these parameters into configParameters.dat, so
you'll get the window at the same place the next time you start up
(also without specifying -x .. -y ..). I have not tried figuring out
the size of the display and providing "left" or "right" option (it's
at least for me not obvious how to do this, what to do in case of more
than 1 monitor attached, etc). I hope the absolute placement (keeping
a record in configParameters.dat) is good enough.

Please let me know in case there are problems or side effects.

Cheers,
--U.

**Comment by lantone** [comment]
Hi Urs,

Thanks for implementing that!  So... one complication.  I'm trying to add this on top of the prod-12 tag we're using during production, but the PixGui.cc code has changed substantially in the meantime, and it doesn't *quite* work as expected.  It looks like you're using the fWidth and fHeight parameters to set the on-screen position of the gui.  However, in the prod-12 version those are still used to set the actual height/width of the window.  So, if I use, for instance "-y 200", the gui window moves 200 pixels from the top of my screen but it also resizes to 200 pixels high.  Do you see an easy way around this?  It's not a crucial feature, so if it's too much trouble to fix the backwards compatibility that's no problem.

Thanks,
Jamie

**Comment by ursl** [comment]
Hi Jamie,

my initial reaction would be that this is not for a patched prod-12.

I think there must be somewhere another means of controlling where
ROOT puts the frame (because on different computers and different root
versions here I see the frames appearing at different places).
However, I don't know it.

The obvious fix would be to not abuse the old member variables, I guess.

If you really want it, I would propose that you make a PR for the
production branch.

Cheers,
--U.

PS: Sorry, the trigger people just told me to come up with new L1 seed
for our analysis, I don't have much spare time at the moment.

**Comment by lantone** [comment]
Hi Urs,

I agree, it would impossible to expect every new commit to be backwards-compatible with every old tag...

I can confirm that it works as advertised in the master branch, if we really want it we can always just check out the master for that session.  

At the end of the day, keeping your signal events from getting thrown away at L1 is probably a much better use of your time :-)

**Comment by ursl** [comment]
I think this can be closed now.

**Comment by lantone** [comment]
agreed
