### ISSUE TITLE
Possible Conflict with Scientific Linux 6.8

### ISSUE THREAD

**Issue by jking79** [psi46/pxar#437]
For the last several weeks we have developed a problem where pxar will occasionally cause the session to exit as if we had logged out.  
The screen will go black then come back to the log in screen.
This most often happens when pxar exits, though it seems to have occurred during a test twice.
Our System Adminasrator thinks this caused by a conflict with the recent auto upgrade of Scientific Linux to version 6.8.
We are using the fermilab prod-12 version of pixar.
Is there a known issue with pxar and SL6.8?  could there be a library incompatibility that is causing the xwindows server to crash when pxar exits?

**Comment by simonspa** [comment]
Hi Jack,

Did you recompile pxar after the system upgrade? Maybe one of the dependencies or the glibc has been upgraded during the process.

Am 13. August 2016 04:59:49 MESZ, schrieb Jack W King III <notifications@github.com>:

**Comment by jking79** [comment]
Hi 
yes , we reran cmake and recompiled.

**Comment by simonspa** [comment]
Hi,  other than that I'm not aware of any problems. If you are able to produce a backtrace of the issue it might be helpful for further investigations.

Am 14. August 2016 04:36:26 MESZ, schrieb Jack W King III <notifications@github.com>:

**Comment by ursl** [comment]
Hi Jack, 

does this happen when when you hit the pxar window "X" (the close button/widget of the window on its top title bar) or do you hit the "exit" button of pxar? 

What window manager are you running? Gnome? KDE? (sorry if these are no longer relevant, it's been a while since I was interested in linux window managers). Does this problem appear in more than one window manager? Does it appear when you connect remotely from another computer?

Cheers,
--U.

**Comment by jking79** [comment]
Hi Urs,

On Aug 15, 2016, at 4:09 AM, Urs Langenegger <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jack,

does this happen when when you hit the pxar window "X" (the close button/widget of the window on its top title bar) or do you hit the "exit" button of pxar?

It happens when we hit the “exit” button of pixar, randomly as for as we can tell.  It also seems to occur if the pxar GUI window closes for any reason.
This does not happen every time, today it was occurring once every 4 or 5 time we closed out of pxar.

I will have to test it from command line or remote.  We do not use pxar in those setups.
I will look through the logs once more, but there does not seem to be any unusual issues recorded.


What window manager are you running? Gnome? KDE? (sorry if these are no longer relevant, it's been a while since I was interested in linux window managers). Does this problem appear in more than one window manager? Does it appear when you connect remotely from another computer?


We are running a Scientific Lynux 6.8.

Cheers,
--U.

**Comment by ursl** [comment]
Hi Jack, 

Scientific Linux 6.8 is an OS, not a [window manager](https://en.wikipedia.org/wiki/Window_manager). It has nothing/not much to do with how windows are arranged on a screen, etc. Somewhere in your configuration you (I mean "one") defines which window manager is used. I don't know whether SL comes with a standard one and I have no idea whether you are indeed running the standard. The reason why I am asking is that the problem might be on the window manager side (and this would be diagnosed if it only happens when running one window manager, but not the other). If the problem appears every 4-5 closings then this should not be too cumbersome to find out. 

Many thanks. 

Cheers,
--U.

**Comment by jking79** [comment]
Urs,


Jack,

The base windowing system is  X11 Windows .  SL uses by default the
GNOME desktop which includes the  metacity  window manager.

Alan

Alan,

We utilize xwindows?

Jack

On Aug 15, 2016, at 2:11 PM, Urs Langenegger <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jack,

Scientific Linux 6.8 is an OS, not a window manager<https://en.wikipedia.org/wiki/Window_manager>. It has nothing/not much to do with how windows are arranged on a screen, etc. Somewhere in your configuration you (I mean "one") defines which window manager is used. I don't know whether SL comes with a standard one and I have no idea whether you are indeed running the standard. The reason why I am asking is that the problem might be on the window manager side (and this would be diagnosed if it only happens when running one window manager, but not the other). If the problem appears every 4-5 closings then this should not be too cumbersome to find out.

Many thanks.

Cheers,
--U.

**Comment by ursl** [comment]
Hi all,

can you please try a different one? I think SL6.8 should also have KDE
which should have a different window manager (KWin?) Alternatively,
sl6.8 seems to also have icewm, but not installed by default.

What SL version did you have beforehand? SL6.7? From the release notes
there nothing would indicate a potential problem for me at least.

Cheers,
--U.

**Comment by jking79** [comment]
Unfortunately this is the system that we use to run our X-ray testing setup. It is mandatory that we have this system operational at this point in time so we are going to revert the machine to an earlier version of the OS.  

Thank You.

**Comment by jking79** [comment]
We reverted xwindows to the version prior to the upgrade to 6.8.  We have not had a re-occurrence of this issue since that time.  If will obtain the details of what was done and post them here.

**Comment by jking79** [comment]
Alan Letz, the System Administrator for PHSX at KU, indicated that he:
"I downgraded all the  xorg-x11-*  packages to their previous versions."
This solved the issue for us.
