### ISSUE TITLE
Critical readout error for layer 1 modules

### ISSUE THREAD

**Issue by lickteig-m** [psi46/pxar#441]
After a timing test of a layer 1 module, e.g. during the pretest, pXar starts to throw critical errors and does not finish the test successfully:

[12:23:46.753]    ERROR: <datapipe.cc/CheckEventValidity:L523> Channel 0 Number of ROCs (1) != Token Chain Length (2)
[12:23:46.764]    ERROR: <hal.cc/daqAllEvents:L1695> Channels report mismatching event numbers: 1 1 17 17 17 1 1 
[12:23:46.764] CRITICAL: <hal.cc/addCondensedData:L2076> Error in DAQ: Channels report mismatching event numbers: 1 1 17 17 17 1 1  Aborting test.
[12:23:46.764] CRITICAL: <PixTestPretest.cc/findWorkingPixel:L1160> pXar execption: Channels report mismatching event numbers: 1 1 17 17 17 1 1 

Observations:
- This does only happen for layer 1 modules.
- Restarting pXar after the timing test does not lead to that error.
- Merge commit 9fd5948 is still working, a3bbeaa adds the error.
- The mismatching event numbers have almost always exactly this pattern.

**Comment by simonspa** [comment]
Hi Martin,

a3bbeaa is a merge commit. If you use `git bisect` you can find the actual offender and fix this.

/Simon

**Comment by schuetzepaul** [comment]
Hi Martin,

it looks to me as if the timing is not set correctly to the TBMs.
The error comes in with this certain commit, because Simon and I added an exception there, which in my eyes is necessary. Looking at the event numbers you get, this is definitely critical.

I'm trying to understand that issue, but since we do not have a Layer 1 module on hand at DESY, it will be tough for me. Hence, could you please print me an example of your configParameters file?

I have the suspicion, that the timings and resets sent from [here](https://github.com/psi46/pxar/blob/master/tests/PixTestPretest.cc#L507) are not sent to all TBM cores due to [this loop](https://github.com/psi46/pxar/blob/master/tests/PixTest.cc#L2446), since there should be four of them, right? Maybe you could check on that for me and give me some feedback.

Paul

**Comment by starodum** [comment]
Hi Paul,

thanks for taking care about L1 module SW. I think Martin is not working anymore on this project. 
You mention that you do not have L1 module at DESY. If you wish one we could send it to you. Danile Pitzl is here till the end of the week and I hope he will agree to take a module with him. Let me know, please.

Andrey

**Comment by schuetzepaul** [comment]
Hi Andrey,

sure, if you have one module to spare, that would be of help, yes.

Paul

**Comment by schuetzepaul** [comment]
Hi again,

thank you very much for sending a L1 module, this helps a lot!

The issue was actually the hard-coded loop mentioned earlier. This should be fixed now.
However, I still observe errors for the first findWorkingPixel after the findtiming, but the test itself ends up to be successful. This is something we also observed during our cold calibration procedures during the production.
I'll leave this thread open until we find a solution to that, although you will be able to run the test now.

Paul

**Comment by simonspa** [comment]
This means, that the checks should stay in and PR #443 should be adapted accordingly before merging.

**Comment by ursl** [comment]
Closed
